# Site settings
title: Anedotas.pt
description: Só as melhores anedotas!
baseurl: ""
url: "http://anedotas.pt"
permalink: :title

# Build settings
markdown: kramdown
exclude: ['node_modules', 'Gruntfile.js', 'package.json']

highlighter: pygments

# YB Settings
excerpt_separator: <!-- mais -->
paginate: 4
comments: false
